// Generated by cc5x-helper from cdl_proto.py (P1) -- DO NOT EDIT.
// Single-source CDL protocol constants, shared by the CC5X target stub
// and the STM32 probe firmware (cc5x-debug-probe 04 SS 4, 05).
#ifndef CDL_PROTO_H
#define CDL_PROTO_H

// --- CDL protocol constants (CDL v0.1) ---
#define CDL_PROTO_MAJOR   0
#define CDL_PROTO_MINOR   1
#define CDL_FLAG          0x7E
#define CDL_ESC           0x7D
#define CDL_ESC_XOR       0x20
#define CDL_CRC_POLY      0x07

#define CDL_T_HELLO     0x01
#define CDL_T_TRACE     0x02
#define CDL_T_LOG       0x03
#define CDL_T_MEM_DATA  0x04
#define CDL_T_BP_HIT    0x05
#define CDL_T_ACK       0x06
#define CDL_T_NAK       0x07
#define CDL_T_PING      0x81
#define CDL_T_READ_MEM  0x82
#define CDL_T_WRITE_MEM 0x83
#define CDL_T_SET_BP    0x84
#define CDL_T_CLR_BP    0x85
#define CDL_T_CONTINUE  0x86
#define CDL_T_SET_TRACE 0x87

#define CDL_NAK_BAD_ADDR    1
#define CDL_NAK_SIDE_EFFECT 2
#define CDL_NAK_WRITE_DENIED 3
#define CDL_NAK_BAD_LEN     4
#define CDL_NAK_UNKNOWN_TYPE 5
#define CDL_NAK_BAD_BP      6

// --- probe-origin envelope types (cc5x-debug-probe relay.c) ---
#define CDL_P_RELAY    0xF0
#define CDL_P_STATUS   0xF1

#endif // CDL_PROTO_H
