"""cdl_protogen.py -- emit C from the single-source CDL spec (cdl_proto).

The *device-independent* protocol constants -- framing, CRC, message TYPE codes,
NAK codes -- are formatted here in exactly ONE place. Both the per-device target
stub header (debuggen._render_header) and the standalone ``cdl_proto.h`` (shared
with the STM32 probe firmware) render from ``render_proto_defines()``, so the C
``#define``s cannot drift from each other or from the spec (05 SS 4.2).

This stays a thin string emitter; all values come from cdl_proto.
"""
from __future__ import annotations

from . import cdl_proto as proto


def render_proto_defines() -> list[str]:
    """The device-independent CDL ``#define`` block, as a list of C source lines.

    Byte-for-byte the constant section debuggen has always emitted into each
    cdl_monitor_<dev>.h, now sourced once from cdl_proto so the per-device header
    and cdl_proto.h are guaranteed identical (the empty-golden-diff invariant,
    05 SS 5)."""
    major, minor = proto.CDL_PROTOCOL_VERSION
    lines = [
        f"// --- CDL protocol constants (CDL v{major}.{minor}) ---",
        f"#define CDL_PROTO_MAJOR   {major}",
        f"#define CDL_PROTO_MINOR   {minor}",
        f"#define CDL_FLAG          0x{proto.CDL_FLAG:02X}",
        f"#define CDL_ESC           0x{proto.CDL_ESC:02X}",
        f"#define CDL_ESC_XOR       0x{proto.CDL_ESC_XOR:02X}",
        f"#define CDL_CRC_POLY      0x{proto.CDL_CRC_POLY:02X}",
        "",
    ]
    for name, code in {**proto.MSG_TYPES_T2H, **proto.MSG_TYPES_H2T}.items():
        lines.append(f"#define CDL_T_{name:<9} 0x{code:02X}")
    lines.append("")
    for name, code in proto.NAK_CODES.items():
        lines.append(f"#define CDL_NAK_{name:<11} {code}")
    lines.append("")
    return lines


def render_c_header() -> str:
    """Render the standalone ``cdl_proto.h`` shared by the CC5X target stub and
    the STM32 probe firmware. It carries the device-independent shared block plus
    the probe-origin envelope types (0xF0/0xF1), which the target stub does not
    emit (it never originates them) but the probe/host side needs (05 SS 4.2)."""
    guard = "CDL_PROTO_H"
    lines = [
        "// Generated by cc5x-helper from cdl_proto.py (P1) -- DO NOT EDIT.",
        "// Single-source CDL protocol constants, shared by the CC5X target stub",
        "// and the STM32 probe firmware (cc5x-debug-probe 04 SS 4, 05).",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        *render_proto_defines(),
        "// --- probe-origin envelope types (cc5x-debug-probe relay.c) ---",
    ]
    for name, code in proto.MSG_TYPES_PROBE.items():
        lines.append(f"#define CDL_P_{name:<8} 0x{code:02X}")
    lines.append("")
    lines.append(f"#endif // {guard}")
    return "\n".join(lines) + "\n"
